# Generated by Django 5.1.1 on 2024-10-09 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Элемент корзины',
                'verbose_name_plural': 'Элементы корзины',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_date', models.DateField(auto_now_add=True, verbose_name='Дата отправления')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name='Дата прибытия')),
                ('from_field', models.CharField(blank=True, db_column='from', max_length=1024, null=True, verbose_name='Адрес отправления')),
                ('to', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Адрес прибытия')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Принят в обработку'), ('paid', 'Оплачен'), ('shipped', 'Отгружен'), ('delivered', 'Доставлен'), ('canceled', 'Отменен'), ('returned', 'Возвращен')], default='pending', max_length=10, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общая цена')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общая цена')),
            ],
            options={
                'verbose_name': 'Элемент заказа',
                'verbose_name_plural': 'Элементы заказа',
            },
        ),
    ]
