# Generated by Django 5.1.1 on 2024-10-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_categories_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', related_query_name='category', to='store.category', verbose_name='Категории'),
        ),
    ]
